################ English language ##################
[ja]
languageName = "Ja"
languageCode = "ja"
contentDir = "content/japanese"
weight = 1

################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 3
